### ISSUE TITLE
Netwerkclasses opstellen

### ISSUE THREAD

**Issue by tristandb** [wouwouwou/project_module_3#9]

**Comment by tristandb** [comment]
summon @jjkramok

**Comment by jjkramok** [comment]
El le Arrivé, Hoe assign ik mezelf? Of kan maar 1 iemand geassigned worden?

**Comment by wouwouwou** [comment]
Er kan indd maar 1 iemand ge-assigned worden...

**Comment by Gerryflap** [comment]
De Netwerkclassen kunnen nu berichtjes versturen, verdere Protrocol implementatie volgt.
